// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm2kOIOQxFEXhtZ78j69UL8En8vBwb_ec',
    appId: '1:380259446181:web:d254efdc7c24db48664c4c',
    messagingSenderId: '380259446181',
    projectId: 'story-points-b387e',
    authDomain: 'story-points-b387e.firebaseapp.com',
    storageBucket: 'story-points-b387e.appspot.com',
    measurementId: 'G-T3L53LWHTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1lRIwH40nGLlWpAQ90ESuNWZ6JnI6is',
    appId: '1:380259446181:android:771e1b97a37c0c44664c4c',
    messagingSenderId: '380259446181',
    projectId: 'story-points-b387e',
    storageBucket: 'story-points-b387e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIlyzvV3eh42k8IAPjkhBqyYQRG5sH5E',
    appId: '1:380259446181:ios:491e359c3d83c5c9664c4c',
    messagingSenderId: '380259446181',
    projectId: 'story-points-b387e',
    storageBucket: 'story-points-b387e.appspot.com',
    iosClientId: '380259446181-9ido4pao579gqup9qmgm33b2cts2osfs.apps.googleusercontent.com',
    iosBundleId: 'ru.whitebug.storyClean',
  );
}
