name: story_data
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.1.17
  dartz: ^0.10.1
  json_serializable: ^6.2.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  story_core:
    path: '../story_core'
  story_domain:
    path: '../story_domain'

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1

flutter:
