name: story_core
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
